# Generated by Django 4.2.11 on 2024-03-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='reviewer',
        ),
    ]
